leftnav:
- identifier: f03094f3-6e60-d35c-d0bb-ed00551f4c2f
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 32a22e0d-e0ad-d673-42ce-41445297fce7
  name: Introduction, Energy Basics & Human Power
  url: /video_galleries/intro-energy-basics-human-power/
  weight: 20
- identifier: bd09c1cc-93fd-481d-3945-6e105dc16816
  name: Energy Storage; Measurement Lab
  url: /video_galleries/energy-storage/
  weight: 30
- identifier: 70e2edb1-3971-cd3b-0091-3ae541bcdecc
  name: Lighting, Biogas
  url: /video_galleries/lighting-biogas/
  weight: 40
- identifier: 97d18199-d8e1-30f9-6762-504a4894e1bc
  name: Solar
  url: /video_galleries/solar/
  weight: 50
- identifier: 5dd5186b-4a86-f3ff-771b-545e19e9b505
  name: Wind and Micro-Hydro
  url: /video_galleries/wind-micro-hydro
  weight: 60
- identifier: 40a90435-c335-4575-5ca5-aed11bc98c6a
  name: Cooking, Stoves & Fuel
  url: /video_galleries/cooking-stoves-fuel
  weight: 70
- identifier: 374104f0-f3d9-30af-2e10-57b34aa6c451
  name: Trip Planning and Preparations
  url: /video_galleries/week-7-trip-planning-and-preparations
  weight: 80
- identifier: fb9d6e56-eac4-97fb-24b4-6d3ac31a62da
  name: Community Partner Trips
  url: /video_galleries/week-8-nicaragua-trip
  weight: 90
- identifier: b769b31f-283d-ae0e-ca5f-75068d997bdb
  name: Projects
  url: /video_galleries/projects/
  weight: 100
- identifier: cc396362-e27a-a416-9fbb-66fd1cb19b76
  name: Project Results
  parent: b769b31f-283d-ae0e-ca5f-75068d997bdb
  url: /video_galleries/projects/project-results
  weight: 110
